# -*- coding: utf-8 -*-
"""volume bola

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TPzw2HAklgW0mCu8Um9w_SxXXxkkVfEx

Menghitung volume bola
"""

print("Menghitung volume bola")
r=int(input("Masukan Jari-jari = "))

phi=22/7
volume=4/3*(phi*r*r*r)

print("Jawaban: ")
print("Volume Bola Adalah = ", volume)